### ISSUE TITLE
Выбор разделов для импорта

### ISSUE THREAD

**Issue by kernusr** [Joomline/YandexXML#1]
В чём смысл показывать в фильтре для импорта разделы, которые сняты с публикации?
Если это "баг", то я PR закину, с правкой поля выбора разделов
Если это "фича", то поясните в чём смысл, пожалуйста!

**Comment by zikkuratvk** [comment]
Скорей всего ни кто не задумывался, что они могут отключены быть :-) закидывай PR.
Еще там скорей всего работа с картинками у жумшопинга устарела.

**Comment by kernusr** [comment]
https://github.com/Joomline/YandexXML/pull/2
